@@include('../../bower_components/jquery/dist/jquery.min.js')
@@include('../../bower_components/bootstrap/dist/js/bootstrap.bundle.min.js')
// @@include('../../bower_components/slick-carousel/slick/slick.js')
// @@include('../../bower_components/magnific-popup/dist/jquery.magnific-popup.min.js')
// @@include('../../bower_components/jquery.maskedinput/dist/jquery.maskedinput.min.js')
// @@include('../../bower_components/jquery-validation/dist/jquery.validate.min.js')
// @@include('../../bower_components/tablesorter/js/jquery.tablesorter.js')
// @@include('../../bower_components/jquery-ui/jquery-ui.min.js')